modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "cobblemon_weather"
version = "${version}"
displayName = "Cobblemon Weather"
authors = "LiquidSilverAce"
description = '''
Overworld weather driven by Cobblemon battle moves and abilities, with a configurable player whitelist.
'''
#logoFile = ""

[[dependencies.cobblemon_weather]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.215,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_weather]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_weather]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemon_weather]]
modId = "cobblemon"
type = "optional"
versionRange = "[1.7.3,1.9)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemon_weather]]
modId = "particlerain"
type = "optional"
versionRange = "[3.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "cobblemon_weather.mixins.json"